In [52]:
import numpy as np 
from numpy import genfromtxt #Load data from a text file, with missing values handled as specified.
from numpy.random import *  # for random sampling
from numpy import genfromtxt #Load data from a text file, with missing values handled as specified.
import scipy.linalg as slin #Linear algebra functions
import pylab #Found in the package pyqt
from pylab import *  # for plotting
import networkx as nx
import sys, os
import re
from pylab import *  # for plotting
import geopandas as gpd

%load_ext autoreload
%autoreload 2

from general_loader import GeneralData
from geometry_loader import GeometryData
from hormones_loader import HormonesData
from cellset_parser import parse_cellset
from network_builder import NetworkBuilder
from hydraulic_loader import HydraulicData
from boundary_loader import BoundaryData
from prepare_paraview import prepare_geometrical_properties


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
general_config='./extdata/Maize_General.xml'
geometry_config='./extdata/Geometry.xml'
hydraulic_config='./extdata/Hydraulics.xml'
boundary_condition_config='./extdata/Maize_BC_kr.xml'
hormones_config='./extdata/Maize_Hormones_Carriers.xml'
cellset_file='./extdata/current_root.xml'
outdir=os.getcwd()

: 

: 

In [ ]:


def is_equal(a, b):
    return((a == b) | ((a != a) & (b != b)))

[1/5] Importing data
  Loading general parameters...
  Loading geometry parameters...
  Loading hormone parameters...


: 

: 

In [ ]:
print('[1/5] Importing data')
    general = GeneralData(general_config)
    geometry = GeometryData(geometry_config)
    hormones = HormonesData(hormones_config)
    hydraulic = HydraulicData(hydraulic_config)
    boundary = BoundaryData(boundary_condition_config)

    #Set path
    newpath=outdir + '/' + geometry.plant_name + '/'

    if not os.path.exists(newpath):
        os.makedirs(newpath)
        
    passage_cell_ID=[]
    
    print('[2/5] Creating the network')
    network = NetworkBuilder()
    # Build network structure
    network.build_network(general, geometry, hormones, cellset_file)

    position=nx.get_node_attributes(network.graph,'position') #Updates nodes XY positions (micrometers)
    indice=nx.get_node_attributes(network.graph,'indice') #Node indices (walls, junctions and cells)

    paraview = prepare_geometrical_properties(general, network, hormones, position, indice)
    locals().update(paraview)


[2/5] Creating the network
  Creating wall, junction and cell nodes...
  Creating membrane connections...
  Ranking cells by tissue type and distance from root center...


: 

: 

In [ ]:
network.create_layer_discretization()

: 

: 

[[  0.        ]
 [  0.35105688]
 [ 11.85098812]
 [ 37.73340675]
 [ 65.95893245]
 [ 96.67881333]
 [109.5922866 ]
 [120.06374088]]
[[  0.        ]
 [  0.35105688]
 [ 11.85098812]
 [ 37.73340675]
 [ 65.95893245]
 [ 96.67881333]
 [109.5922866 ]
 [120.06374088]
 [131.18498235]]
[[  0.        ]
 [  0.35105688]
 [ 11.85098812]
 [ 37.73340675]
 [ 65.95893245]
 [ 96.67881333]
 [109.5922866 ]
 [120.06374088]
 [131.18498235]
 [147.85572243]
 [147.85572243]
 [147.85572243]
 [147.85572243]]
[[  0.        ]
 [  0.35105688]
 [ 11.85098812]
 [ 37.73340675]
 [ 65.95893245]
 [ 96.67881333]
 [109.5922866 ]
 [120.06374088]
 [131.18498235]
 [147.85572243]
 [147.85572243]
 [147.85572243]
 [147.85572243]
 [176.40891559]]
[[0.00000000e+00]
 [3.51056881e-01]
 [1.18509881e+01]
 [3.77334067e+01]
 [6.59589324e+01]
 [9.66788133e+01]
 [1.09592287e+02]
 [1.20063741e+02]
 [1.31184982e+02]
 [1.47855722e+02]
 [1.47855722e+02]
 [1.47855722e+02]
 [1.47855722e+02]
 [1.76408916e+02]
 [2.14951251e+02]
 [2.54842300e+02]
 [2.

: 

: 

In [ ]:
distance_from_center

array([[3.51056881e-01],
       [1.18509881e+01],
       [3.77334067e+01],
       [6.59589324e+01],
       [9.66788133e+01],
       [1.09592287e+02],
       [1.20063741e+02],
       [1.31184982e+02],
       [1.47855722e+02],
       [1.47855722e+02],
       [1.47855722e+02],
       [1.47855722e+02],
       [1.76408916e+02],
       [2.14951251e+02],
       [2.54842300e+02],
       [2.94791807e+02],
       [3.35177635e+02],
       [3.74153093e+02],
       [4.08287127e+02],
       [4.08287127e+02],
       [4.25977777e+02]])

: 

: 

In [ ]:
network.distance_from_center

array([3.51056881e-01, 1.18509881e+01, 3.77334067e+01, 6.59589324e+01,
       9.66788133e+01, 1.09592287e+02, 1.20063741e+02, 1.31184982e+02,
       1.47855722e+02, 1.47855722e+02, 1.47855722e+02, 1.47855722e+02,
       1.76408916e+02, 2.14951251e+02, 2.54842300e+02, 2.94791807e+02,
       3.35177635e+02, 3.74153093e+02, 4.08287127e+02, 4.08287127e+02,
       4.25977777e+02])

: 

: 

In [ ]:
network.r_discret

array([21,  7,  1,  4,  6,  2,  1])

: 

: 